import type { Profile } from "./types.js";

/** Render the profile as human-readable Markdown (context.md). */
export function renderMarkdown(p: Profile): string {
  const lines: string[] = [];
  lines.push(`# ${p.name} — Context`);
  lines.push("");
  if (p.headline) lines.push(`> ${p.headline}`);
  if (p.bio) {
    lines.push("");
    lines.push(p.bio);
  }
  lines.push("");

  if (p.currentRole) {
    lines.push("## Current Role");
    lines.push(`${p.currentRole.role} @ ${p.currentRole.company}`);
    lines.push("");
  }

  const c = p.contact;
  const contactLines = [
    c.email && `- Email: ${c.email}`,
    c.website && `- Website: ${c.website}`,
    c.github && `- GitHub: ${c.github}`,
    c.linkedin && `- LinkedIn: ${c.linkedin}`,
    c.twitter && `- Twitter/X: ${c.twitter}`,
  ].filter(Boolean) as string[];
  if (contactLines.length) {
    lines.push("## Contact");
    lines.push(...contactLines);
    lines.push("");
  }

  if (p.skills.length) {
    lines.push("## Skills");
    lines.push(p.skills.map((s) => `- ${s}`).join("\n"));
    lines.push("");
  }

  if (p.learning.length) {
    lines.push("## Currently Learning");
    lines.push(p.learning.map((s) => `- ${s}`).join("\n"));
    lines.push("");
  }

  if (p.github) {
    const g = p.github;
    lines.push("## GitHub");
    if (g.contributionsLastYear != null)
      lines.push(`- Contributions (last year): ${g.contributionsLastYear}`);
    if (g.pullRequestsOpened != null)
      lines.push(`- Pull Requests opened: ${g.pullRequestsOpened}`);
    if (g.publicRepos != null) lines.push(`- Public repositories: ${g.publicRepos}`);
    if (g.totalStars != null) lines.push(`- Total stars: ${g.totalStars}`);
    if (g.topRepos.length) {
      lines.push("- Top repositories:");
      for (const r of g.topRepos) {
        lines.push(`  - ${r.fullName} (★${r.stars})${r.description ? ` — ${r.description}` : ""}`);
      }
    }
    lines.push("");
  }

  if (p.openSource.length) {
    lines.push("## Open Source");
    for (const o of p.openSource) {
      lines.push(`- ${o.name}${o.role ? ` (${o.role})` : ""}${o.description ? ` — ${o.description}` : ""}`);
    }
    lines.push("");
  }

  if (p.projects.length) {
    lines.push("## Projects");
    for (const proj of p.projects) {
      lines.push(`- ${proj.name}${proj.description ? ` — ${proj.description}` : ""}`);
    }
    lines.push("");
  }

  if (p.blogs.length) {
    lines.push("## Recent Blogs");
    for (const b of p.blogs.slice(0, 20)) {
      const date = b.date ? ` (${b.date.slice(0, 10)})` : "";
      lines.push(`- ${b.title}${date} — ${b.link}`);
    }
    lines.push("");
  }

  if (p.experience.length) {
    lines.push("## Experience");
    for (const e of p.experience) {
      const range = [e.start, e.end].filter(Boolean).join(" – ");
      lines.push(`- ${e.role} @ ${e.company}${range ? ` (${range})` : ""}`);
    }
    lines.push("");
  }

  lines.push(`_Generated by personal-context at ${p.generatedAt}_`);
  return lines.join("\n");
}

/** Render the profile as JSON (profile.json). */
export function renderJson(p: Profile): string {
  return JSON.stringify(p, null, 2);
}

/** Render an llms.txt suitable for AI consumption. */
export function renderLlmsTxt(p: Profile): string {
  const lines: string[] = [];
  lines.push(`# ${p.name}`);
  if (p.headline) lines.push(`> ${p.headline}`);
  lines.push("");
  if (p.bio) {
    lines.push(p.bio);
    lines.push("");
  }
  if (p.currentRole) {
    lines.push(`Current role: ${p.currentRole.role} at ${p.currentRole.company}`);
  }
  if (p.skills.length) lines.push(`Skills: ${p.skills.join(", ")}`);
  if (p.learning.length) lines.push(`Currently learning: ${p.learning.join(", ")}`);
  if (p.openSource.length)
    lines.push(`Open source: ${p.openSource.map((o) => o.name).join(", ")}`);
  if (p.github) {
    const g = p.github;
    const parts = [
      g.contributionsLastYear != null && `${g.contributionsLastYear} contributions/yr`,
      g.publicRepos != null && `${g.publicRepos} repos`,
      `${g.profileUrl}`,
    ].filter(Boolean);
    lines.push(`GitHub: ${parts.join(", ")}`);
  }
  if (p.blogs.length) {
    lines.push("");
    lines.push("## Recent writing");
    for (const b of p.blogs.slice(0, 15)) {
      lines.push(`- [${b.title}](${b.link})`);
    }
  }
  return lines.join("\n");
}

/** A short one-paragraph AI brief about the person. */
export function renderSummary(p: Profile): string {
  const role = p.currentRole
    ? `${p.currentRole.role} at ${p.currentRole.company}`
    : (p.headline ?? "a builder");
  const focus = p.learning.length
    ? p.learning.slice(0, 4).join(", ")
    : p.skills.slice(0, 4).join(", ");
  const oss = p.openSource.length
    ? ` and actively contributes to ${p.openSource.slice(0, 3).map((o) => o.name).join(", ")}`
    : "";
  const blogCount = p.blogs.length ? ` Has published ${p.blogs.length}+ recent posts.` : "";
  return `${p.name} is ${role}, focused on ${focus}${oss}.${blogCount}`.replace(/\s+/g, " ").trim();
}
